language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  # command to install dependencies
install:
  - make init
# command to run tests
script:
  - make test